

platform:ios , '8.0'
use_frameworks!
target '5dou' do

pod 'AFNetworking', '~>3.1.0'
pod 'SVProgressHUD', '~>2.0.4'
pod 'IQKeyboardManager' , '~>4.0.7'
pod 'JSONModel' , '~>1.7.0'
pod 'SDWebImage', '~>3.8.2'
pod 'MJRefresh', '~>3.1.12'
pod 'Masonry', '~>1.0.2'
pod 'TZImagePickerController', '~>1.7.1'
pod 'YYText', '~>1.0.7'
pod 'Colours', '~>5.13.0'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/WeChat'
pod 'AvoidCrash'
#pod 'dsBridge'




end
